defaults:
  actions:
    queue:
      method: squash
      commit_message_template: |
        {%- set commit_msg = body | get_section("## Description", "") -%}
        {%- set lines = commit_msg.split("\n") -%}
        {%- set trailer_prefix = "\n" -%}  {# Default to newline #}
        {%- set trailer_test = "" -%}
        {%- if lines|length >= 2 -%}
            {%- set trailer_test = lines[-2] | replace(": ", ":IDENTIFIER:") -%}
            {%- if "IDENTIFIER" in trailer_test -%}
                {%- set trailer_prefix = "" -%}
            {%- endif -%}
        {%- endif -%}
        {{ title }}

        {{ commit_msg }}{{ trailer_prefix }}Pull-Request: #{{ number }}.

queue_rules:
  - name: default
    conditions: []